/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ourcraft;

import java.util.List;

public class App {
    private static final List<String> ADJECTIVES = List.of("Turbo", "Neon", "Quantum", "Lava", "Stealth");
    private static final List<String> NOUNS = List.of("Creeper", "Pickaxe", "Parrot", "Ghast", "Beacon");

    public String getGreeting() {
        return "ourcraft // Definitely Not Minecraft™";
    }

    public String buildJokeDroneBrief(int creativitySeed) {
        int safeSeed = Math.floorMod(creativitySeed, ADJECTIVES.size() * NOUNS.size());
        String codename = ADJECTIVES.get(safeSeed % ADJECTIVES.size())
                + " "
                + NOUNS.get((safeSeed / ADJECTIVES.size()) % NOUNS.size());
        return String.join(
                "\n",
                "🚁 Joke PR Mission Brief",
                "Codename: " + codename,
                "Objective: make it work and be cool",
                "Status: absolutely vibing");
    }

    public static void main(String[] args) {
        App app = new App();
        int seed = args.length > 0 ? args[0].hashCode() : 6;
        System.out.println(app.getGreeting());
        System.out.println();
        System.out.println(app.buildJokeDroneBrief(seed));
    }
}
