/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ourcraft;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertTrue(classUnderTest.getGreeting().contains("ourcraft"), "app should reference ourcraft");
    }

    @Test void droneBriefHasCoreVibeLines() {
        App classUnderTest = new App();
        String brief = classUnderTest.buildJokeDroneBrief(6);

        assertAll(
                () -> assertTrue(brief.contains("🚁 Joke PR Mission Brief")),
                () -> assertTrue(brief.contains("Objective: make it work and be cool")),
                () -> assertTrue(brief.contains("Status: absolutely vibing")));
    }
}
